---
- name: Create Scripts dir
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/Scripts
    state: directory
    owner: {{ ansible_user }}

- name: Install prereqs
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3-pip
      - terminator
      - fish
      - neo4j
      - vim-gtk3
      - zaproxy
  when: ansible_facts["distribution"] == "Kali"
