---
- name: Get Elastic Container Repo
  ansible.builtin.git:
    repo: https://github.com/peasead/elastic-container.git
    dest: /home/{{ ansible_user }}/elastic-container
    force: true

- name: Set up Env file
  ansible.builtin.template:
    src: elk-env.j2
    dest: /home/{{ ansible_user }}/elastic-container/.env
    mode: 0644

- name: Bring up Stack
  ansible.builtin.command:
    chdir: /home/{{ ansible_user }}/elastic-container
    cmd: ./elastic-container.sh start
