---
- name: Restart Windows Splunk UF Service
  ansible.windows.win_service:
    name: SplunkForwarder
    state: restarted

- name: Start Linux Splunk UF Service
  ansible.builtin.systemd:
    name: SplunkForwarder
    state: started
