- name: Install Elastic Agent
  hosts: all
  vars_prompt:
    - name: siem_ip
      prompt: SIEM IP
      private: false
    - name: enrollment_token
      prompt: Fleet Enrollment Token
      private: false
  roles:
    - elastic-agent
