---
- name: Configure Malware Analysis Machines
  hosts: [malwarelab-win-victim, malwarelab-win-analysis, malwarelab-kali]
  vars_prompt:
    - name: siem_ip
      prompt: "Enter SIEM Server IP"
      private: false
    - name: fleet_server_token
      prompt: "Enter Fleet Server Token (Blank for Splunk)"
      private: false
    - name: siem_password
      prompt: "Enter Splunk Password (Blank for Elastic)"
      private: true
  roles:
    - role: rdp
      tags: ["always"]
    - role: seclab-kali
      when: ansible_facts["distribution"] == "Kali"
      tags: ["always"]
    - role: attack-box
      become: true
      tags: ["always"]
      when: ansible_facts["distribution"] == "Kali"
    - role: malwarelab-analysis-linux
      become: true
      tags: ["always"]
      when: ansible_facts["distribution"] == "Kali"
    - role: malwarelab-analysis-win
      tags: ["always"]
      when: ansible_facts["os_family"] == "Windows"
    - role: elastic-agent
      tags: ["elastic"]
      when: ansible_facts["os_family"] == "Windows"
    - role: sysmon
      when: ansible_facts["os_family"] == "Windows"
      tags: ["always"]
    - role: splunk-uf
      tags: ["splunk"]
