- name: Start Pktmon
  gather_facts: true
  hosts: windows-hosts
  tasks:
  - name: Execute Script
    ansible.windows.win_powershell:
      script: | 
        PktMon start --capture --pkt-size 0 
      chdir: C:\Users\{{ ansible_user }}\Downloads
    register: result
  
  - name: Show Output
    ansible.builtin.debug:
      msg: "{{ result['host_out'] }}"

  - name: Show Errors
    ansible.builtin.debug:
      msg: "{{ result['host_err'] }}"