- name: Create a Windows File Server
  hosts: windows-hosts
  gather_facts: true
  tasks:
  - name: Add File Server Feature
    win_feature: >
      name=FS-FileServer
      include_management_tools=yes
      include_sub_features=yes
      state=present
    register: res

  - name: Reboot
    win_reboot:
    when: res.reboot_required