network:
  ethernets:
    ens18:
      dhcp4: false
      dhcp-identifier: mac
      addresses:
        - 192.168.99.3/24
      nameservers:
          addresses: [8.8.8.8, 8.8.4.4]
      routes:
      - to: 0.0.0.0/0
        via: 192.168.99.1
        metric: 99
  version: 2